version: '3'
services:
  speed-actuator-engine:
    image: darlynvailatti/speedactuator
    container_name: speed_actuator
    ports:
      - '3001:3001'
    networks:
      - backend
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'
