export enum RedisConstants {
  REDIS_CLIENT_PUBLISHER = 'REDIS_CLIENT_PUBLISHER',
  REDIS_CLIENT_SUBSCRIBER = 'REDIS_CLIENT_PUBLISHER',

  SENSOR_DETECTION_BROKER_CHANNEL = 'SENSOR_DETECTION',
  TEST_UPDATE_STATE_CHANNEL = 'TEST_UPDATE_STATE',

  TEST_VIEW_CHANNEL_WS = 'TEST_VIEW_CHANNEL_WS',
  REDIS_REPOSITORY_CLIENT_NAME = 'REDIS_REPOSITORY_CLIENT_NAME',
  REDIS_URL = 'REDIS_URL',
}

export enum ConstantsApiTags {
  VIEW_API_TAG = 'view',
  EXECUTION_API_TAG = 'execution',
  DETECTION_API_TAG = 'detection',
  LAB_API_TAG = 'laboratory',
}
